### ISSUE TITLE
False positive some virus scanners

### ISSUE THREAD

**Issue by Blocky38** [MinnDevelopment/discord-webhooks#57]
Some virus Scanners (Bitdefender + Windows Defender + ...) detect https://github.com/MinnDevelopment/discord-webhooks/blob/master/src/main/java/club/minnced/discord/webhook/receive/ReadonlyMessage.java as infected with "Java.Trojan".
Can any developer of this project take a look into it?

**Comment by MinnDevelopment** [comment]
I scanned the file with windows defender just now, I have 0 reports of any viruses. I can assure you this library does not have any trojan in it. I think you might be scanning the javadoc jar, which usually gets detected as a trojan due to the embedded js scripts for search. This is looks like it might be a trojan to a virus detector, but it is not.

**Comment by Blocky38** [comment]
I am already in contact with the laboratory of Microsoft and Bitdefender to remove this false positive. From Microsoft side I have a confirmation.

**Comment by Blocky38** [comment]
I got the answer auf both that it is added to the whitelist. @MinnDevelopment
