### ISSUE TITLE
Allow sending webhook messages with slack format

### ISSUE THREAD

**Issue by BestClaws** [MinnDevelopment/discord-webhooks#96]
Other discord libraries discord js for example support sending webhook messages with slack's webhook format this has some benifits (been a while since I last checked) that spam audit logs less.for example they let you specify the message author name (which would otherwise be a new audit log entry if done the usual way)

**Comment by MinnDevelopment** [comment]
This library implements discord webhooks, using their format, since any other format is only supposed to be used when it's unavoidable.

To send a slack compatible message, you can use any existing slack webhook library instead and simply pass in the discord webhook URL (see [slack-api-client](https://github.com/slackapi/java-slack-sdk)).

I do not want to support and maintain compatibility with other external API formats, which are foreign to discord.

**Comment by BestClaws** [comment]
understandable thank you.
